language: android
android:
  components:
    - platform-tools
    - build-tools-22.0.1
    - android-22
    - extra-android-support
    - extra-android-m2repository

script: ./gradlew clean build test
